info:
  model: int-scaffold
packages:
- gitBranch: release/1.0.0
  gitServerName: specSource
  gitUrl: https://github.com/aadi-tripathi
  gitUsername: aadi-tripathi
  name: ThursProProject
version: 1.0.0
